#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use Spraed\DumpThis\Tool\DumpApplication;

$app = new DumpApplication();
$app->run();
?>