#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use Spraed\DumpThis\Tool\DumpApplication;

// $app = new DumpApplication();
// $app->run();

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

$application = new DumpApplication();
$application->run($input);
?>